services:
  # backend:
  #   build:
  #     context: .
  #     dockerfile: dockerfile
  #   env_file: .env
  #   depends_on:
  #     - postgres
  #     - aws-s3
  #   networks:
  #     - my-network
  postgres:
    container_name: godb
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: local.env
    networks:
      - my-network
  ## S3 Service
  minio:
    container_name: aws-s3
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./docker/minio-storage:/data
    command: server --console-address ":9001" /data
    env_file: local.env
    restart: always
    networks:
      - my-network
volumes:
  postgres_data:
  minio_storage:
networks:
  my-network:
    driver: bridge
